name: Deploy FeedsApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # Jika menggunakan port SSH non-standar, tambahkan: port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /path/to/FeedsApp
            git pull origin main
            # Misal, jika kamu menggunakan pm2 untuk menjalankan FeedsApp:
            pm2 restart feedsapp
            # Atau jika FeedsApp dijalankan dengan systemd, kamu bisa melakukan:
            # sudo systemctl restart feedsapp
